# Generated by Django 5.0.2 on 2024-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('administrator', 'Administrator'), ('delivery', 'Delivery')], max_length=20),
        ),
    ]
