# Generated by Django 5.0.2 on 2024-11-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('meal_image', models.ImageField(upload_to='meal_images/')),
                ('meal_description', models.TextField()),
                ('meal_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
