# Generated by Django 5.0.2 on 2024-11-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
            ],
        ),
    ]
