# Generated by Django 5.0.2 on 2024-11-02 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='meal_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sections.meal'),
        ),
    ]
