# Generated by Django 5.0.2 on 2024-11-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_remove_appointment_meal_id_appointment_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='UNPAID', max_length=10),
        ),
    ]
