# Generated by Django 5.0.2 on 2024-11-02 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_appointment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.meal'),
        ),
    ]
